/**
 * Recapiti uffici giudiziari del distretto della Corte d'Appello di Napoli.
 * Fonte: dati istituzionali del Ministero della Giustizia / Corte d'Appello.
 *
 * Dataset piatto, pensato per la ricerca testuale (denominazione, comune,
 * provincia, circondario, tipologia, indirizzo, telefono, email).
 */

export type TipoUfficio =
  | 'CorteAppello'
  | 'CorteAssiseAppello'
  | 'CorteAssise'
  | 'ProcuraGenerale'
  | 'Tribunale'
  | 'TribunaleMinorenni'
  | 'ProcuraMinorenni'
  | 'TribunaleSorveglianza'
  | 'UfficioSorveglianza'
  | 'TribunaleAcquePubbliche'
  | 'SezioneDistaccata'
  | 'Procura'
  | 'GiudiceDiPace';

export interface RecapitoUfficio {
  id: string;
  tipo: TipoUfficio;
  /** Etichetta breve della tipologia, mostrata nella card */
  tipoLabel: string;
  /** Denominazione completa (es. "Tribunale di Napoli") */
  denominazione: string;
  /** Circondario di appartenenza (es. "Napoli", "Avellino"...). Vuoto per uffici distrettuali */
  circondario?: string;
  /** Comune di sede */
  comune: string;
  /** Provincia (sigla) */
  provincia: string;
  /** Indirizzo completo (può contenere più sedi) */
  indirizzo: string;
  /** CAP principale */
  cap?: string;
  /** Telefono(i) */
  telefono?: string;
  /** Email istituzionale @giustizia.it */
  email?: string;
  /** Fax */
  fax?: string;
  /** Note libere (es. "settore civile", "settore penale", "I sezione"...) */
  note?: string;
}

export const RECAPITI_UFFICI: RecapitoUfficio[] = [
  // ========== UFFICI DISTRETTUALI ==========
  {
    id: 'corte-appello-napoli',
    tipo: 'CorteAppello',
    tipoLabel: "Corte d'Appello",
    denominazione: "Corte d'Appello di Napoli",
    comune: 'Napoli',
    provincia: 'NA',
    indirizzo: "Piazza E. De Nicola (settore civile e amministrativo) — Piazza Cenni, Nuovo Palazzo di Giustizia (settore penale)",
    cap: '80139 / 80143',
    telefono: '081 2237111',
    email: 'ca.napoli@giustizia.it',
    fax: '081 282124',
    note: 'Centralino unico',
  },
  {
    id: 'procura-generale-napoli',
    tipo: 'ProcuraGenerale',
    tipoLabel: 'Procura Generale',
    denominazione: "Procura Generale della Repubblica presso la Corte d'Appello di Napoli",
    comune: 'Napoli',
    provincia: 'NA',
    indirizzo: 'Piazza Cenni — Nuovo Palazzo di Giustizia',
    cap: '80143',
    telefono: '081 2237111',
    email: 'pg.napoli@giustizia.it',
    fax: '081 2234449',
  },
  {
    id: 'tribunale-minorenni-napoli',
    tipo: 'TribunaleMinorenni',
    tipoLabel: 'Tribunale per i Minorenni',
    denominazione: 'Tribunale per i Minorenni di Napoli',
    comune: 'Napoli',
    provincia: 'NA',
    indirizzo: 'Viale Colli Aminei, 42',
    cap: '80131',
    telefono: '081 7449111',
    email: 'tribmin.napoli@giustizia.it',
    fax: '081 7414964 / 7419132',
  },
  {
    id: 'procura-minorenni-napoli',
    tipo: 'ProcuraMinorenni',
    tipoLabel: 'Procura presso il Tribunale per i Minorenni',
    denominazione: 'Procura della Repubblica presso il Tribunale per i Minorenni di Napoli',
    comune: 'Napoli',
    provincia: 'NA',
    indirizzo: 'Viale Colli Aminei, 44',
    cap: '80131',
    telefono: '081 7447111',
    email: 'procmin.napoli@giustizia.it',
    fax: '081 7415403 / 7418512',
  },
  {
    id: 'tribunale-sorveglianza-napoli',
    tipo: 'TribunaleSorveglianza',
    tipoLabel: 'Tribunale di Sorveglianza',
    denominazione: 'Tribunale di Sorveglianza di Napoli',
    comune: 'Napoli',
    provincia: 'NA',
    indirizzo: 'Nuovo Palazzo di Giustizia — Torre C, Centro Direzionale',
    cap: '80143',
    telefono: '081 2234955 / 954',
    email: 'tribsorv.napoli@giustizia.it',
    fax: '081 2234257 / 303',
  },
  {
    id: 'ufficio-sorveglianza-avellino',
    tipo: 'UfficioSorveglianza',
    tipoLabel: 'Ufficio di Sorveglianza',
    denominazione: 'Ufficio di Sorveglianza di Avellino',
    comune: 'Avellino',
    provincia: 'AV',
    indirizzo: 'Piazza A. Moro, c/o Palazzo di Giustizia',
    cap: '83100',
    telefono: '0825 7971',
    email: 'uffsorv.avellino@giustizia.it',
    fax: '0825 23481',
  },
  {
    id: 'ufficio-sorveglianza-napoli',
    tipo: 'UfficioSorveglianza',
    tipoLabel: 'Ufficio di Sorveglianza',
    denominazione: 'Ufficio di Sorveglianza di Napoli',
    comune: 'Napoli',
    provincia: 'NA',
    indirizzo: 'Nuovo Palazzo di Giustizia — Torre C, Centro Direzionale',
    cap: '80143',
    telefono: '081 2234955 / 954',
    email: 'uffsorv.napoli@giustizia.it',
    fax: '081 2234257 / 303',
  },
  {
    id: 'ufficio-sorveglianza-smcv',
    tipo: 'UfficioSorveglianza',
    tipoLabel: 'Ufficio di Sorveglianza',
    denominazione: 'Ufficio di Sorveglianza di Santa Maria Capua Vetere',
    comune: 'Santa Maria Capua Vetere',
    provincia: 'CE',
    indirizzo: 'Via Albana',
    cap: '81055',
    telefono: '0823 892111 / 512',
    email: 'uffsorv.santamariacapuavetere@giustizia.it',
    fax: '0823 798811',
  },
  {
    id: 'tribunale-acque-pubbliche-napoli',
    tipo: 'TribunaleAcquePubbliche',
    tipoLabel: 'Tribunale Regionale delle Acque Pubbliche',
    denominazione: 'Tribunale Regionale delle Acque Pubbliche di Napoli',
    comune: 'Napoli',
    provincia: 'NA',
    indirizzo: 'Piazza Enrico De Nicola — Castel Capuano',
    cap: '80139',
    telefono: '081 2237285 / 299',
    fax: '081 286068',
  },
  {
    id: 'corte-assise-appello-napoli',
    tipo: 'CorteAssiseAppello',
    tipoLabel: "Corte di Assise d'Appello",
    denominazione: "Corte di Assise d'Appello di Napoli",
    comune: 'Napoli',
    provincia: 'NA',
    indirizzo: 'Centro Direzionale — Nuovo Palazzo di Giustizia, Torre C, piano 17',
    cap: '80143',
    telefono: '081 2234613/12 (I sez.) — 2234611/19 (II sez.) — 2234623/10 (IV sez.) — 2234618 (direzione)',
    email: 'concetta.laragione@giustizia.it; maurizio.macri@giustizia.it',
    fax: '081 2234609 (I e II sez.) — 2234623',
  },

  // ========== CIRCONDARIO: ARIANO IRPINO ==========
  {
    id: 'tribunale-ariano-irpino',
    tipo: 'Tribunale',
    tipoLabel: 'Tribunale',
    denominazione: 'Tribunale di Ariano Irpino',
    circondario: 'Ariano Irpino',
    comune: 'Ariano Irpino',
    provincia: 'AV',
    indirizzo: 'Piazza Mancini',
    cap: '83031',
    telefono: '0825 8291',
    email: 'tribunale.arianoirpino@giustizia.it',
    fax: '0825 828171 / 383',
    note: 'Centralino',
  },
  {
    id: 'procura-ariano-irpino',
    tipo: 'Procura',
    tipoLabel: 'Procura della Repubblica',
    denominazione: 'Procura della Repubblica presso il Tribunale di Ariano Irpino',
    circondario: 'Ariano Irpino',
    comune: 'Ariano Irpino',
    provincia: 'AV',
    indirizzo: 'Piazza S. Mancini',
    cap: '83031',
    telefono: '0825 8291',
    email: 'procura.arianoirpino@giustizia.it',
    fax: '0825 828170',
  },
  {
    id: 'gdp-ariano-irpino',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Ariano Irpino',
    circondario: 'Ariano Irpino',
    comune: 'Ariano Irpino',
    provincia: 'AV',
    indirizzo: 'Piazza P.S. Mancini (zona Calvario)',
    cap: '83031',
    telefono: '0825 8291',
    email: 'gdp.arianoirpino@giustizia.it',
    fax: '0825 829288',
  },
  {
    id: 'gdp-castel-baronia',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Castel Baronia',
    circondario: 'Ariano Irpino',
    comune: 'Castel Baronia',
    provincia: 'AV',
    indirizzo: 'Piazza Dante, 1',
    cap: '83040',
    telefono: '0827 92009',
    email: 'giudice.dipace@virgilio.it',
    fax: '0827 92725',
  },
  {
    id: 'gdp-grottaminarda',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Grottaminarda',
    circondario: 'Ariano Irpino',
    comune: 'Grottaminarda',
    provincia: 'AV',
    indirizzo: 'Piazza Castello',
    cap: '83035',
    telefono: '0825 445540',
    fax: '0825 429068',
  },
  {
    id: 'gdp-mirabella-eclano',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Mirabella Eclano',
    circondario: 'Ariano Irpino',
    comune: 'Mirabella Eclano',
    provincia: 'AV',
    indirizzo: "Via S. Angelo",
    cap: '83036',
    telefono: '0825 438244',
    fax: '0825 438127',
  },

  // ========== CIRCONDARIO: AVELLINO ==========
  {
    id: 'tribunale-avellino',
    tipo: 'Tribunale',
    tipoLabel: 'Tribunale',
    denominazione: 'Tribunale di Avellino',
    circondario: 'Avellino',
    comune: 'Avellino',
    provincia: 'AV',
    indirizzo: "Piazza d'Armi",
    cap: '83100',
    telefono: '0825 7971',
    email: 'tribunale.avellino@giustizia.it',
    fax: '0825 24041',
    note: 'Centralino',
  },
  {
    id: 'sezdist-cervinara',
    tipo: 'SezioneDistaccata',
    tipoLabel: 'Sezione Distaccata di Tribunale',
    denominazione: 'Sezione Distaccata di Tribunale di Cervinara',
    circondario: 'Avellino',
    comune: 'Cervinara',
    provincia: 'AV',
    indirizzo: 'Via Ciriaco di Roma',
    cap: '83012',
    telefono: '0824 836120',
    email: 'tribunale.avellino.cervinara@giustizia.it',
    fax: '0824 836120',
  },
  {
    id: 'procura-avellino',
    tipo: 'Procura',
    tipoLabel: 'Procura della Repubblica',
    denominazione: 'Procura della Repubblica presso il Tribunale di Avellino',
    circondario: 'Avellino',
    comune: 'Avellino',
    provincia: 'AV',
    indirizzo: "Piazza d'Armi",
    cap: '83100',
    telefono: '0825 7971',
    email: 'procura.avellino@giustizia.it',
    fax: '0825 38201',
  },
  {
    id: 'gdp-avellino',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Avellino',
    circondario: 'Avellino',
    comune: 'Avellino',
    provincia: 'AV',
    indirizzo: 'Via Mancini, 1 — Palazzo De Peruta',
    cap: '83100',
    telefono: '0825 39348',
    email: 'gdp.avellino@giustizia.it',
    fax: '0825 31961',
  },
  {
    id: 'gdp-cervinara',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Cervinara',
    circondario: 'Avellino',
    comune: 'Cervinara',
    provincia: 'AV',
    indirizzo: 'Via Ciriaco di Roma',
    cap: '83012',
    telefono: '0824 836120 / 839111',
    email: 'gdp.cervinara@giustizia.it',
    fax: '0824 838121',
  },
  {
    id: 'gdp-chiusano-san-domenico',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Chiusano di San Domenico',
    circondario: 'Avellino',
    comune: 'Chiusano di San Domenico',
    provincia: 'AV',
    indirizzo: 'Via Carcere',
    cap: '83040',
    telefono: '0825 985039',
    fax: '0825 985039',
  },
  {
    id: 'gdp-lauro',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Lauro',
    circondario: 'Avellino',
    comune: 'Lauro',
    provincia: 'AV',
    indirizzo: 'Via A. Fuselli',
    cap: '83023',
    telefono: '0827 8240223',
    fax: '0827 8240223',
  },
  {
    id: 'gdp-montoro-superiore',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Montoro Superiore',
    circondario: 'Avellino',
    comune: 'Montoro Superiore',
    provincia: 'AV',
    indirizzo: 'Piazza IV Novembre',
    cap: '83026',
    telefono: '0825 523047',
    fax: '0825 523108',
  },
  {
    id: 'corte-assise-avellino',
    tipo: 'CorteAssise',
    tipoLabel: 'Corte di Assise',
    denominazione: 'Corte di Assise di Avellino',
    circondario: 'Avellino',
    comune: 'Avellino',
    provincia: 'AV',
    indirizzo: "Piazza d'Armi",
    cap: '83100',
    telefono: '0825 7971',
    email: 'tribunale.avellino@giustizia.it',
    fax: '0825 797221',
  },

  // ========== CIRCONDARIO: BENEVENTO ==========
  {
    id: 'tribunale-benevento',
    tipo: 'Tribunale',
    tipoLabel: 'Tribunale',
    denominazione: 'Tribunale di Benevento',
    circondario: 'Benevento',
    comune: 'Benevento',
    provincia: 'BN',
    indirizzo: 'Viale Raffaele De Caro',
    cap: '82100',
    telefono: '0824 309111',
    email: 'tribunale.benevento@giustizia.it',
    fax: '0824 312891',
    note: 'Centralino',
  },
  {
    id: 'sezdist-airola',
    tipo: 'SezioneDistaccata',
    tipoLabel: 'Sezione Distaccata di Tribunale',
    denominazione: 'Sezione Distaccata di Tribunale di Airola',
    circondario: 'Benevento',
    comune: 'Airola',
    provincia: 'BN',
    indirizzo: 'Via Fossa Arena',
    cap: '82011',
    telefono: '0823 712266',
    fax: '0823 712280',
  },
  {
    id: 'sezdist-guardia-sanframondi',
    tipo: 'SezioneDistaccata',
    tipoLabel: 'Sezione Distaccata di Tribunale',
    denominazione: 'Sezione Distaccata di Tribunale di Guardia Sanframondi',
    circondario: 'Benevento',
    comune: 'Guardia Sanframondi',
    provincia: 'BN',
    indirizzo: 'Via Padre Adolfo De Blasio',
    cap: '82034',
    telefono: '0824 864029',
    fax: '0824 817140',
  },
  {
    id: 'procura-benevento',
    tipo: 'Procura',
    tipoLabel: 'Procura della Repubblica',
    denominazione: 'Procura della Repubblica presso il Tribunale di Benevento',
    circondario: 'Benevento',
    comune: 'Benevento',
    provincia: 'BN',
    indirizzo: 'Viale Raffaele De Caro',
    cap: '82100',
    telefono: '0824 309111',
    email: 'procura.benevento@giustizia.it',
    fax: '0824 312889',
  },
  {
    id: 'gdp-san-giorgio-del-sannio',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di San Giorgio del Sannio',
    circondario: 'Benevento',
    comune: 'San Giorgio del Sannio',
    provincia: 'BN',
    indirizzo: 'Via Cardilli',
    cap: '82018',
    telefono: '0824 40594',
    fax: '0824 40594',
  },
  {
    id: 'gdp-airola',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Airola',
    circondario: 'Benevento',
    comune: 'Airola',
    provincia: 'BN',
    indirizzo: 'Via Fossa Arena',
    cap: '82011',
    telefono: '0823 711168',
    email: 'gdp.airola@giustizia.it',
    fax: '0823 711168',
  },
  {
    id: 'gdp-benevento',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Benevento',
    circondario: 'Benevento',
    comune: 'Benevento',
    provincia: 'BN',
    indirizzo: 'Via A. Mazzoni, 17/21',
    cap: '82100',
    telefono: '0824 311299',
    email: 'gdp.benevento@giustizia.it',
    fax: '0824 311299',
  },
  {
    id: 'gdp-cerreto-sannita',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Cerreto Sannita',
    circondario: 'Benevento',
    comune: 'Cerreto Sannita',
    provincia: 'BN',
    indirizzo: 'Via Mastrobuoni',
    cap: '82032',
    telefono: '0824 861422',
    fax: '0824 861422',
  },
  {
    id: 'gdp-colle-sannita',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Colle Sannita',
    circondario: 'Benevento',
    comune: 'Colle Sannita',
    provincia: 'BN',
    indirizzo: 'Corso Umberto I, 20',
    cap: '82024',
    telefono: '0824 931067',
    fax: '0824 931067',
  },
  {
    id: 'gdp-guardia-sanframondi',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Guardia Sanframondi',
    circondario: 'Benevento',
    comune: 'Guardia Sanframondi',
    provincia: 'BN',
    indirizzo: 'Piazza Canalicchio',
    cap: '82034',
    telefono: '0824 817768',
    email: 'gdp.guardiasanframondi@giustizia.it',
    fax: '0824 817768',
  },
  {
    id: 'gdp-montesarchio',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Montesarchio',
    circondario: 'Benevento',
    comune: 'Montesarchio',
    provincia: 'BN',
    indirizzo: 'Via S. Giovanni',
    cap: '82016',
    telefono: '0824 834759',
    fax: '0824 831312',
  },
  {
    id: 'gdp-san-giorgio-la-molara',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di San Giorgio La Molara',
    circondario: 'Benevento',
    comune: 'San Giorgio La Molara',
    provincia: 'BN',
    indirizzo: 'Piazza Madonna di Fatima',
    cap: '82020',
    telefono: '0824 983495',
    fax: '0824 983495',
  },
  {
    id: 'gdp-santagata-de-goti',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: "Giudice di Pace di Sant'Agata de' Goti",
    circondario: 'Benevento',
    comune: "Sant'Agata de' Goti",
    provincia: 'BN',
    indirizzo: 'Viale Picone',
    cap: '82019',
    telefono: '0823 953113',
    fax: '0823 953113',
  },
  {
    id: 'gdp-solopaca',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Solopaca',
    circondario: 'Benevento',
    comune: 'Solopaca',
    provincia: 'BN',
    indirizzo: 'Via Granatelle',
    cap: '82036',
    telefono: '0824 977499',
    fax: '0824 977499',
  },
  {
    id: 'gdp-vitulano',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Vitulano',
    circondario: 'Benevento',
    comune: 'Vitulano',
    provincia: 'BN',
    indirizzo: 'Via Mercuri, 17',
    cap: '82038',
    telefono: '0824 878407',
    fax: '0824 878407',
  },
  {
    id: 'corte-assise-benevento',
    tipo: 'CorteAssise',
    tipoLabel: 'Corte di Assise',
    denominazione: 'Corte di Assise di Benevento',
    circondario: 'Benevento',
    comune: 'Benevento',
    provincia: 'BN',
    indirizzo: 'Via Raffaele De Caro',
    cap: '82100',
    telefono: '0824 309465',
    fax: '0824 312891',
    note: 'Segreteria amministrativa',
  },

  // ========== CIRCONDARIO: GIUGLIANO IN CAMPANIA ==========
  {
    id: 'tribunale-giugliano',
    tipo: 'Tribunale',
    tipoLabel: 'Tribunale',
    denominazione: 'Tribunale di Giugliano in Campania',
    circondario: 'Giugliano in Campania',
    comune: 'Giugliano in Campania',
    provincia: 'NA',
    indirizzo: 'Dato non disponibile',
  },
  {
    id: 'sezdist-pozzuoli',
    tipo: 'SezioneDistaccata',
    tipoLabel: 'Sezione Distaccata di Tribunale',
    denominazione: 'Sezione Distaccata di Tribunale di Pozzuoli',
    circondario: 'Giugliano in Campania',
    comune: 'Pozzuoli',
    provincia: 'NA',
    indirizzo: 'Via Celle, 2',
    cap: '80078',
    telefono: '081 8554111 / 5265323',
    email: 'tribunale.napoli.pozzuoli@giustizia.it',
    fax: '081 5268925',
  },
  {
    id: 'sezdist-marano',
    tipo: 'SezioneDistaccata',
    tipoLabel: 'Sezione Distaccata di Tribunale',
    denominazione: 'Sezione Distaccata di Tribunale di Marano di Napoli',
    circondario: 'Giugliano in Campania',
    comune: 'Marano di Napoli',
    provincia: 'NA',
    indirizzo: 'Via Lario',
    cap: '80016',
    telefono: '081 5863912 / 921',
    email: 'tribunale.napoli.maranodinapoli@giustizia.it',
    fax: '081 7428379',
  },
  {
    id: 'procura-giugliano',
    tipo: 'Procura',
    tipoLabel: 'Procura della Repubblica',
    denominazione: 'Procura della Repubblica presso il Tribunale di Giugliano in Campania',
    circondario: 'Giugliano in Campania',
    comune: 'Giugliano in Campania',
    provincia: 'NA',
    indirizzo: 'Dato non disponibile',
  },
  {
    id: 'gdp-pozzuoli',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Pozzuoli',
    circondario: 'Giugliano in Campania',
    comune: 'Pozzuoli',
    provincia: 'NA',
    indirizzo: 'Via Celle, 19',
    cap: '80078',
    telefono: '081 8551417 / 15 / 16',
    fax: '081 5260266',
  },
  {
    id: 'gdp-marano',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Marano di Napoli',
    circondario: 'Giugliano in Campania',
    comune: 'Marano di Napoli',
    provincia: 'NA',
    indirizzo: 'Via Lario',
    cap: '80016',
    telefono: '081 5866646',
    email: 'gdp.maranodinapoli@giustizia.it',
    fax: '081 5866550',
  },
  {
    id: 'gdp-procida',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Procida',
    circondario: 'Giugliano in Campania',
    comune: 'Procida',
    provincia: 'NA',
    indirizzo: "Via Liberta', 10",
    cap: '80079',
    telefono: '081 8967942',
    fax: '081 8967102',
  },

  // ========== CIRCONDARIO: NAPOLI ==========
  {
    id: 'tribunale-napoli-recapiti',
    tipo: 'Tribunale',
    tipoLabel: 'Tribunale',
    denominazione: 'Tribunale di Napoli',
    circondario: 'Napoli',
    comune: 'Napoli',
    provincia: 'NA',
    indirizzo: 'Piazza E. De Nicola (settore civile e amministrativo) — Piazza Cenni, Nuovo Palazzo di Giustizia (settore penale)',
    cap: '80139 / 80143',
    telefono: '081 2237391 / 88',
    email: 'tribunale.napoli@giustizia.it',
    fax: '081 2237652',
  },
  {
    id: 'sezdist-portici',
    tipo: 'SezioneDistaccata',
    tipoLabel: 'Sezione Distaccata di Tribunale',
    denominazione: 'Sezione Distaccata di Tribunale di Portici',
    circondario: 'Napoli',
    comune: 'Portici',
    provincia: 'NA',
    indirizzo: 'Corso Garibaldi, 41',
    cap: '80055',
    telefono: '081 482981 / 7862257',
    fax: '081 270586',
  },
  {
    id: 'sezdist-afragola',
    tipo: 'SezioneDistaccata',
    tipoLabel: 'Sezione Distaccata di Tribunale',
    denominazione: 'Sezione Distaccata di Tribunale di Afragola',
    circondario: 'Napoli',
    comune: 'Afragola',
    provincia: 'NA',
    indirizzo: 'Corso Napoli, 1',
    cap: '80021',
    telefono: '081 8691533 / 1692',
    fax: '081 8526126',
  },
  {
    id: 'sezdist-capri',
    tipo: 'SezioneDistaccata',
    tipoLabel: 'Sezione Distaccata di Tribunale',
    denominazione: 'Sezione Distaccata di Tribunale di Capri',
    circondario: 'Napoli',
    comune: 'Capri',
    provincia: 'NA',
    indirizzo: 'Via Roma, 62',
    cap: '80073',
    telefono: '081 8370287 / 8376389',
    fax: '081 8376389',
  },
  {
    id: 'sezdist-casoria',
    tipo: 'SezioneDistaccata',
    tipoLabel: 'Sezione Distaccata di Tribunale',
    denominazione: 'Sezione Distaccata di Tribunale di Casoria',
    circondario: 'Napoli',
    comune: 'Casoria',
    provincia: 'NA',
    indirizzo: 'Via Pio XII, 130',
    cap: '80026',
    telefono: '081 7573212 / 1209 / 3209',
    fax: '081 7573081',
  },
  {
    id: 'sezdist-frattamaggiore',
    tipo: 'SezioneDistaccata',
    tipoLabel: 'Sezione Distaccata di Tribunale',
    denominazione: 'Sezione Distaccata di Tribunale di Frattamaggiore',
    circondario: 'Napoli',
    comune: 'Frattamaggiore',
    provincia: 'NA',
    indirizzo: 'Via Padre M. Vergara, 16',
    cap: '80027',
    telefono: '081 8801377 / 221',
    fax: '081 8804525',
  },
  {
    id: 'sezdist-ischia',
    tipo: 'SezioneDistaccata',
    tipoLabel: 'Sezione Distaccata di Tribunale',
    denominazione: 'Sezione Distaccata di Tribunale di Ischia',
    circondario: 'Napoli',
    comune: 'Ischia',
    provincia: 'NA',
    indirizzo: 'Via Mazzella, 107',
    cap: '80070',
    telefono: '081 991407 / 922 / 977',
    fax: '081 984051',
  },
  {
    id: 'procura-napoli-recapiti',
    tipo: 'Procura',
    tipoLabel: 'Procura della Repubblica',
    denominazione: 'Procura della Repubblica presso il Tribunale di Napoli',
    circondario: 'Napoli',
    comune: 'Napoli',
    provincia: 'NA',
    indirizzo: 'Centro Direzionale di Napoli',
    cap: '80100',
    telefono: '081 2236111',
    email: 'procura.napoli@giustizia.it',
    fax: '081 2236286 / 6341',
  },
  {
    id: 'gdp-napoli',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Napoli',
    circondario: 'Napoli',
    comune: 'Napoli',
    provincia: 'NA',
    indirizzo: 'Via Foria, ex caserma Garibaldi (civile) — Nuovo Palazzo di Giustizia, Centro Direzionale (penale)',
    cap: '80100',
    telefono: '081 2239302 / 22 / 23 / 24 (civile) — 081 2232011 / 72 (penale)',
    email: 'gdp.napoli@giustizia.it',
    fax: '081 2239231 / 106 / 224 (civile) — 081 2232072 (penale)',
  },
  {
    id: 'gdp-afragola',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Afragola',
    circondario: 'Napoli',
    comune: 'Afragola',
    provincia: 'NA',
    indirizzo: "Corso d'Italia, 33",
    cap: '80021',
    telefono: '081 8512138',
    email: 'gdp.afragola@giustizia.it',
    fax: '081 8512138',
  },
  {
    id: 'gdp-barra',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Barra',
    circondario: 'Napoli',
    comune: 'Barra',
    provincia: 'NA',
    indirizzo: 'Via Bartolo Longo, lotto zero',
    cap: '80147',
    telefono: '081 2580201',
    fax: '081 2580215 / 021',
  },
  {
    id: 'gdp-capri',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Capri',
    circondario: 'Napoli',
    comune: 'Capri',
    provincia: 'NA',
    indirizzo: 'Vicolo Palazzo, 33',
    cap: '80073',
    telefono: '081 8375578',
    email: 'gdp.capri@giustizia.it',
    fax: '081 8375578',
  },
  {
    id: 'gdp-casoria',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Casoria',
    circondario: 'Napoli',
    comune: 'Casoria',
    provincia: 'NA',
    indirizzo: 'Via Pio XII, 130',
    cap: '80026',
    telefono: '081 7577053',
    email: 'gdp.casoria@giustizia.it',
    fax: '081 5405090',
  },
  {
    id: 'gdp-frattamaggiore',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Frattamaggiore',
    circondario: 'Napoli',
    comune: 'Frattamaggiore',
    provincia: 'NA',
    indirizzo: 'Via Vergara, 10',
    cap: '80027',
    telefono: '081 8804418',
    email: 'gdp.frattamaggiore@giustizia.it',
    fax: '081 8801855',
  },
  {
    id: 'gdp-ischia',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Ischia',
    circondario: 'Napoli',
    comune: 'Ischia',
    provincia: 'NA',
    indirizzo: 'Via Mazzella, 107',
    cap: '80070',
    telefono: '081 981088',
    email: 'gdp.ischia@giustizia.it',
    fax: '081 981088',
  },
  {
    id: 'gdp-portici',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Portici',
    circondario: 'Napoli',
    comune: 'Portici',
    provincia: 'NA',
    indirizzo: 'Corso Garibaldi, 43',
    cap: '80055',
    telefono: '081 484300 / 2560201',
    email: 'gdp.portici@giustizia.it',
    fax: '081 484300 / 2560201',
  },
  {
    id: 'corte-assise-napoli',
    tipo: 'CorteAssise',
    tipoLabel: 'Corte di Assise',
    denominazione: 'Corte di Assise di Napoli',
    circondario: 'Napoli',
    comune: 'Napoli',
    provincia: 'NA',
    indirizzo: 'Piazza Cenni',
    cap: '80100',
    telefono: '081 2234953 (centralino) — 2234198 (I sez.) — 2234201 (II sez.) — 2234203 (III sez.) — 2234205 (IV sez.) — 2234208 (V sez.) — 2234199 / 4200 / 4202 / 4204 / 4207 (cancelleria) — 2234213 (dirigenza) — 2234206 (segreteria)',
    email: 'carlo.vigliotti@giustizia.it',
    fax: '081 2234953 — 2234198 (I) — 2234201 (II) — 2234203 (III) — 2234205 (IV) — 2234208 (V) — 2234199 / 4200 / 4202 / 4204 / 4207 (canc.)',
  },

  // ========== CIRCONDARIO: NOLA ==========
  {
    id: 'tribunale-nola',
    tipo: 'Tribunale',
    tipoLabel: 'Tribunale',
    denominazione: 'Tribunale di Nola',
    circondario: 'Nola',
    comune: 'Nola',
    provincia: 'NA',
    indirizzo: 'Piazza G. Bruno — Palazzo Orsini',
    cap: '80035',
    telefono: '081 5117111',
    email: 'tribunale.nola@giustizia.it',
    fax: '081 5117395',
  },
  {
    id: 'procura-nola',
    tipo: 'Procura',
    tipoLabel: 'Procura della Repubblica',
    denominazione: 'Procura della Repubblica presso il Tribunale di Nola',
    circondario: 'Nola',
    comune: 'Nola',
    provincia: 'NA',
    indirizzo: 'Piazza G. Bruno — Palazzo Orsini',
    cap: '80035',
    telefono: '081 5119111',
    email: 'procura.nola@giustizia.it',
    fax: '081 515387 / 88',
  },
  {
    id: 'gdp-nola',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Nola',
    circondario: 'Nola',
    comune: 'Nola',
    provincia: 'NA',
    indirizzo: 'Via Saviano',
    cap: '80035',
    telefono: '081 5125747 / 5757',
    email: 'gdp.nola@giustizia.it',
    fax: '081 5125758',
  },
  {
    id: 'gdp-acerra',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Acerra',
    circondario: 'Nola',
    comune: 'Acerra',
    provincia: 'NA',
    indirizzo: 'Via Falcone Borsellino c/o Pretura',
    cap: '80011',
    telefono: '081 5200545',
    fax: '081 5200546',
  },
  {
    id: 'gdp-cicciano',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Cicciano',
    circondario: 'Nola',
    comune: 'Cicciano',
    provincia: 'NA',
    indirizzo: 'Via Martiri del Terrorismo',
    cap: '80033',
    telefono: '081 8265343',
    fax: '081 8248413 / 8261159',
  },
  {
    id: 'gdp-marigliano',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Marigliano',
    circondario: 'Nola',
    comune: 'Marigliano',
    provincia: 'NA',
    indirizzo: 'Via Firenze',
    cap: '80034',
    telefono: '081 8851820',
    fax: '081 5191355',
  },
  {
    id: 'gdp-ottaviano',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Ottaviano',
    circondario: 'Nola',
    comune: 'Ottaviano',
    provincia: 'NA',
    indirizzo: 'Via Salita Piazza',
    cap: '80044',
    telefono: '081 5288889',
    fax: '081 5288890',
  },
  {
    id: 'gdp-pomigliano',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: "Giudice di Pace di Pomigliano d'Arco",
    circondario: 'Nola',
    comune: "Pomigliano d'Arco",
    provincia: 'NA',
    indirizzo: 'Via Cosimo Miccoli, 50',
    cap: '80038',
    telefono: '081 8031038',
    fax: '081 8841063',
  },
  {
    id: 'gdp-santanastasia',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: "Giudice di Pace di Sant'Anastasia",
    circondario: 'Nola',
    comune: "Sant'Anastasia",
    provincia: 'NA',
    indirizzo: 'Piazza Siano, 2',
    cap: '80048',
    telefono: '081 8982155',
    fax: '081 8982155',
  },

  // ========== CIRCONDARIO: SANT'ANGELO DEI LOMBARDI ==========
  {
    id: 'tribunale-santangelo',
    tipo: 'Tribunale',
    tipoLabel: 'Tribunale',
    denominazione: "Tribunale di Sant'Angelo dei Lombardi",
    circondario: "Sant'Angelo dei Lombardi",
    comune: "Sant'Angelo dei Lombardi",
    provincia: 'AV',
    indirizzo: 'Via Petrile, s.n.c.',
    cap: '83054',
    telefono: '0827 23152',
    email: 'tribunale.santangelodeilombardi@giustizia.it',
    fax: '0827 24164 (segr.) — 24433 (penale) — 24218 (G.U.P.)',
  },
  {
    id: 'procura-santangelo',
    tipo: 'Procura',
    tipoLabel: 'Procura della Repubblica',
    denominazione: "Procura della Repubblica presso il Tribunale di Sant'Angelo dei Lombardi",
    circondario: "Sant'Angelo dei Lombardi",
    comune: "Sant'Angelo dei Lombardi",
    provincia: 'AV',
    indirizzo: 'Piazza Umberto I',
    cap: '83054',
    telefono: '0827 202111',
    email: 'procura.santangelodeilombardi@giustizia.it',
    fax: '0827 23254 / 562',
  },
  {
    id: 'gdp-santangelo',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: "Giudice di Pace di Sant'Angelo dei Lombardi",
    circondario: "Sant'Angelo dei Lombardi",
    comune: "Sant'Angelo dei Lombardi",
    provincia: 'AV',
    indirizzo: "Localita' Boschetto, 1",
    cap: '83054',
    telefono: '0827 23872',
    email: 'gdp.santangelodeilombardi@giustizia.it',
    fax: '0827 23872',
  },
  {
    id: 'gdp-calabritto',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Calabritto',
    circondario: "Sant'Angelo dei Lombardi",
    comune: 'Calabritto',
    provincia: 'AV',
    indirizzo: 'Via S. Allende',
    cap: '83040',
    telefono: '0827 52121',
    fax: '0827 52121',
  },
  {
    id: 'gdp-calitri',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Calitri',
    circondario: "Sant'Angelo dei Lombardi",
    comune: 'Calitri',
    provincia: 'AV',
    indirizzo: 'Piazza Salvatore Scoca',
    cap: '83045',
    telefono: '0827 30409',
    fax: '0827 30409',
  },
  {
    id: 'gdp-frigento',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Frigento',
    circondario: "Sant'Angelo dei Lombardi",
    comune: 'Frigento',
    provincia: 'AV',
    indirizzo: 'Piazza Municipio',
    cap: '83040',
    telefono: '0825 444105',
    fax: '0825 444105',
  },
  {
    id: 'gdp-lacedonia',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Lacedonia',
    circondario: "Sant'Angelo dei Lombardi",
    comune: 'Lacedonia',
    provincia: 'AV',
    indirizzo: 'Via De Sanctis, 9',
    cap: '83046',
    telefono: '0827 84223',
    email: 'gdplacedonia@tiscalinet.it',
    fax: '0827 84223',
  },
  {
    id: 'gdp-montella',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Montella',
    circondario: "Sant'Angelo dei Lombardi",
    comune: 'Montella',
    provincia: 'AV',
    indirizzo: 'Via Don Minzoni',
    cap: '83048',
    telefono: '0827 601642',
    fax: '0827 601642',
  },

  // ========== CIRCONDARIO: SANTA MARIA CAPUA VETERE ==========
  {
    id: 'tribunale-smcv',
    tipo: 'Tribunale',
    tipoLabel: 'Tribunale',
    denominazione: 'Tribunale di Santa Maria Capua Vetere',
    circondario: 'Santa Maria Capua Vetere',
    comune: 'Santa Maria Capua Vetere',
    provincia: 'CE',
    indirizzo: 'Piazza Resistenza (penale) — Via Santagata (civile)',
    cap: '81055',
    telefono: '0823 792111 / 389 (penale) — 0823 792111 (civile)',
    email: 'tribunale.santamariacapuavetere@giustizia.it',
    fax: '0823 849045 (penale) — 797750 / 792874 / 924 (civile)',
  },
  {
    id: 'sezdist-piedimonte-matese',
    tipo: 'SezioneDistaccata',
    tipoLabel: 'Sezione Distaccata di Tribunale',
    denominazione: 'Sezione Distaccata di Tribunale di Piedimonte Matese',
    circondario: 'Santa Maria Capua Vetere',
    comune: 'Piedimonte Matese',
    provincia: 'CE',
    indirizzo: 'Piazza Carmine, 24',
    cap: '81016',
    telefono: '0823 911180',
    fax: '0823 785818',
  },
  {
    id: 'sezdist-aversa',
    tipo: 'SezioneDistaccata',
    tipoLabel: 'Sezione Distaccata di Tribunale',
    denominazione: 'Sezione Distaccata di Tribunale di Aversa',
    circondario: 'Santa Maria Capua Vetere',
    comune: 'Aversa',
    provincia: 'CE',
    indirizzo: 'Via Ettore Corcione',
    telefono: '081 8901655',
    fax: '081 8901271',
  },
  {
    id: 'sezdist-carinola',
    tipo: 'SezioneDistaccata',
    tipoLabel: 'Sezione Distaccata di Tribunale',
    denominazione: 'Sezione Distaccata di Tribunale di Carinola',
    circondario: 'Santa Maria Capua Vetere',
    comune: 'Carinola',
    provincia: 'CE',
    indirizzo: 'Corso Umberto I',
    cap: '81030',
    telefono: '0823 737411',
    email: 'tribunale.santamariacapuavetere.carinola@giustizia.it',
    fax: '0823 737449',
  },
  {
    id: 'sezdist-caserta',
    tipo: 'SezioneDistaccata',
    tipoLabel: 'Sezione Distaccata di Tribunale',
    denominazione: 'Sezione Distaccata di Tribunale di Caserta',
    circondario: 'Santa Maria Capua Vetere',
    comune: 'Caserta',
    provincia: 'CE',
    indirizzo: 'Via Arena, s.n.c.',
    cap: '81100',
    telefono: '0823 276111 (centralino) — 276205 (Dirig.) — 276209 (segr.)',
    fax: '0823 276247 (canc. penale) — 276234 (canc. esec. penale)',
  },
  {
    id: 'sezdist-marcianise',
    tipo: 'SezioneDistaccata',
    tipoLabel: 'Sezione Distaccata di Tribunale',
    denominazione: 'Sezione Distaccata di Tribunale di Marcianise',
    circondario: 'Santa Maria Capua Vetere',
    comune: 'Marcianise',
    provincia: 'CE',
    indirizzo: 'Via De Felice',
    cap: '81025',
    telefono: '0823 827983',
    email: 'tribunale.santamariacapuavetere.marcianise@giustizia.it',
    fax: '0823 826186',
  },
  {
    id: 'procura-smcv',
    tipo: 'Procura',
    tipoLabel: 'Procura della Repubblica',
    denominazione: 'Procura della Repubblica presso il Tribunale di Santa Maria Capua Vetere',
    circondario: 'Santa Maria Capua Vetere',
    comune: 'Santa Maria Capua Vetere',
    provincia: 'CE',
    indirizzo: 'Piazza Resistenza',
    cap: '81055',
    telefono: '0823 792111',
    email: 'procura.santamariacapuavetere@giustizia.it',
    fax: '0823 792413',
  },
  {
    id: 'gdp-piedimonte-matese',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Piedimonte Matese',
    circondario: 'Santa Maria Capua Vetere',
    comune: 'Piedimonte Matese',
    provincia: 'CE',
    indirizzo: 'Via Don Bosco',
    cap: '81016',
    telefono: '0823 786141',
    email: 'gdp.piedimontematese@giustizia.it',
    fax: '0823 786141',
  },
  {
    id: 'gdp-arienzo',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Arienzo',
    circondario: 'Santa Maria Capua Vetere',
    comune: 'Arienzo',
    provincia: 'CE',
    indirizzo: 'Via Roma',
    cap: '81021',
    telefono: '0823 805454',
    fax: '0823 805454',
  },
  {
    id: 'gdp-aversa',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Aversa',
    circondario: 'Santa Maria Capua Vetere',
    comune: 'Aversa',
    provincia: 'CE',
    indirizzo: 'Via E. Corcioni',
    cap: '81031',
    telefono: '0825 8157111 / 205',
    email: 'gdp.aversa@giustizia.it',
    fax: '0825 8901317 / 8157211',
  },
  {
    id: 'gdp-capriati',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Capriati a Volturno',
    circondario: 'Santa Maria Capua Vetere',
    comune: 'Capriati a Volturno',
    provincia: 'CE',
    indirizzo: 'Via Fontanarosa, 4',
    cap: '81014',
    telefono: '0823 944984',
    fax: '0823 944980',
  },
  {
    id: 'gdp-capua',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Capua',
    circondario: 'Santa Maria Capua Vetere',
    comune: 'Capua',
    provincia: 'CE',
    indirizzo: 'Corso Appio, 50',
    cap: '81043',
    telefono: '0823 622800',
    fax: '0823 622881',
  },
  {
    id: 'gdp-carinola',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Carinola',
    circondario: 'Santa Maria Capua Vetere',
    comune: 'Carinola',
    provincia: 'CE',
    indirizzo: 'Corso Umberto I',
    cap: '81030',
    telefono: '0823 737065',
    email: 'gdp.carinola@giustizia.it',
    fax: '0823 737065',
  },
  {
    id: 'gdp-caserta',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Caserta',
    circondario: 'Santa Maria Capua Vetere',
    comune: 'Caserta',
    provincia: 'CE',
    indirizzo: 'Via Arena — frazione S. Benedetto',
    cap: '81100',
    telefono: '0823 321621 / 805',
    email: 'gdp.caserta@giustizia.it',
    fax: '0823 322156',
  },
  {
    id: 'gdp-maddaloni',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Maddaloni',
    circondario: 'Santa Maria Capua Vetere',
    comune: 'Maddaloni',
    provincia: 'CE',
    indirizzo: 'Via Caudina (10ª traversa)',
    cap: '81024',
    telefono: '0823 201370',
    fax: '0823 201370',
  },
  {
    id: 'gdp-marcianise',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Marcianise',
    circondario: 'Santa Maria Capua Vetere',
    comune: 'Marcianise',
    provincia: 'CE',
    indirizzo: 'Via S. Giuliano, 226',
    cap: '81025',
    telefono: '0823 838911 / 12',
    email: 'gdp.marcianise@giustizia.it',
    fax: '0823 837709',
  },
  {
    id: 'gdp-pignataro-maggiore',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Pignataro Maggiore',
    circondario: 'Santa Maria Capua Vetere',
    comune: 'Pignataro Maggiore',
    provincia: 'CE',
    indirizzo: 'Via Vittorio Veneto',
    cap: '81052',
    telefono: '0823 871023',
    fax: '0823 871805',
  },
  {
    id: 'gdp-smcv',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Santa Maria Capua Vetere',
    circondario: 'Santa Maria Capua Vetere',
    comune: 'Santa Maria Capua Vetere',
    provincia: 'CE',
    indirizzo: 'Via Albana — ex caserma M. Fiore',
    cap: '81055',
    telefono: '0823 816223 / 02',
    email: 'gdp.santamariacapuavetere@giustizia.it',
    fax: '0823 816201 / 02',
  },
  {
    id: 'gdp-sessa-aurunca',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Sessa Aurunca',
    circondario: 'Santa Maria Capua Vetere',
    comune: 'Sessa Aurunca',
    provincia: 'CE',
    indirizzo: 'Piazza Castello, 1',
    cap: '81037',
    telefono: '0823 937013',
    fax: '0823 937017',
  },
  {
    id: 'gdp-teano',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Teano',
    circondario: 'Santa Maria Capua Vetere',
    comune: 'Teano',
    provincia: 'CE',
    indirizzo: 'Vico Tanzillo',
    cap: '81057',
    telefono: '0823 875267',
    fax: '0823 875016',
  },
  {
    id: 'gdp-trentola-ducenta',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Trentola-Ducenta',
    circondario: 'Santa Maria Capua Vetere',
    comune: 'Trentola-Ducenta',
    provincia: 'CE',
    indirizzo: 'Via Caruso, 1',
    cap: '81038',
    telefono: '081 8142600',
    fax: '081 81429559',
  },
  {
    id: 'corte-assise-smcv',
    tipo: 'CorteAssise',
    tipoLabel: 'Corte di Assise',
    denominazione: 'Corte di Assise di Santa Maria Capua Vetere',
    circondario: 'Santa Maria Capua Vetere',
    comune: 'Santa Maria Capua Vetere',
    provincia: 'CE',
    indirizzo: 'Piazza Resistenza',
    cap: '81055',
    telefono: '0823 792238',
    fax: '0823 898054',
    note: 'Cancelleria — II sezione penale',
  },

  // ========== CIRCONDARIO: TORRE ANNUNZIATA ==========
  {
    id: 'tribunale-torre-annunziata',
    tipo: 'Tribunale',
    tipoLabel: 'Tribunale',
    denominazione: 'Tribunale di Torre Annunziata',
    circondario: 'Torre Annunziata',
    comune: 'Torre Annunziata',
    provincia: 'NA',
    indirizzo: 'Corso Umberto I',
    cap: '80058',
    telefono: '081 8573210 / 11',
    email: 'tribunale.torreannunziata@giustizia.it',
    fax: '081 8612838',
  },
  {
    id: 'sezdist-sorrento',
    tipo: 'SezioneDistaccata',
    tipoLabel: 'Sezione Distaccata di Tribunale',
    denominazione: 'Sezione Distaccata di Tribunale di Sorrento',
    circondario: 'Torre Annunziata',
    comune: 'Sorrento',
    provincia: 'NA',
    indirizzo: 'Via degli Aranci, 27',
    cap: '80067',
    telefono: '081 8071809',
    email: 'tribunale.torreannunziata.sorrento@giustizia.it',
    fax: '081 8071738',
  },
  {
    id: 'sezdist-castellammare',
    tipo: 'SezioneDistaccata',
    tipoLabel: 'Sezione Distaccata di Tribunale',
    denominazione: 'Sezione Distaccata di Tribunale di Castellammare di Stabia',
    circondario: 'Torre Annunziata',
    comune: 'Castellammare di Stabia',
    provincia: 'NA',
    indirizzo: 'Viale Europa, 436',
    cap: '80053',
    telefono: '081 8711408',
    email: 'tribunale.torreannunziata.castellammaredistabia@giustizia.it',
    fax: '081 8715378',
  },
  {
    id: 'sezdist-gragnano',
    tipo: 'SezioneDistaccata',
    tipoLabel: 'Sezione Distaccata di Tribunale',
    denominazione: 'Sezione Distaccata di Tribunale di Gragnano',
    circondario: 'Torre Annunziata',
    comune: 'Gragnano',
    provincia: 'NA',
    indirizzo: 'Via Vittorio Veneto',
    cap: '80054',
    telefono: '081 8012961 / 1375',
    fax: '081 8013044',
  },
  {
    id: 'sezdist-torre-del-greco',
    tipo: 'SezioneDistaccata',
    tipoLabel: 'Sezione Distaccata di Tribunale',
    denominazione: 'Sezione Distaccata di Tribunale di Torre del Greco',
    circondario: 'Torre Annunziata',
    comune: 'Torre del Greco',
    provincia: 'NA',
    indirizzo: 'Via Campania',
    cap: '80059',
    telefono: '081 8493218 / 325 / 631',
    email: 'tribunale.torreannunziata.torredelgreco@giustizia.it',
    fax: '081 8829195',
  },
  {
    id: 'procura-torre-annunziata',
    tipo: 'Procura',
    tipoLabel: 'Procura della Repubblica',
    denominazione: 'Procura della Repubblica presso il Tribunale di Torre Annunziata',
    circondario: 'Torre Annunziata',
    comune: 'Torre Annunziata',
    provincia: 'NA',
    indirizzo: 'Corso Umberto I',
    cap: '80058',
    telefono: '081 8573205',
    email: 'procura.torreannunziata@giustizia.it',
    fax: '081 8613462',
  },
  {
    id: 'gdp-pompei',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Pompei',
    circondario: 'Torre Annunziata',
    comune: 'Pompei',
    provincia: 'NA',
    indirizzo: 'Via Lepanto',
    cap: '80045',
    telefono: '081 8504845',
    fax: '081 8635380',
  },
  {
    id: 'gdp-castellammare',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Castellammare di Stabia',
    circondario: 'Torre Annunziata',
    comune: 'Castellammare di Stabia',
    provincia: 'NA',
    indirizzo: 'Viale Europa, 43',
    cap: '80053',
    telefono: '081 8726006 / 5497',
    email: 'gdp.castellammaredistabia@giustizia.it',
    fax: '081 8726063',
  },
  {
    id: 'gdp-gragnano',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Gragnano',
    circondario: 'Torre Annunziata',
    comune: 'Gragnano',
    provincia: 'NA',
    indirizzo: 'Via Vittorio Veneto',
    cap: '80054',
    telefono: '081 8795078',
    email: 'gdp.gragnano@giustizia.it',
    fax: '081 8795914',
  },
  {
    id: 'gdp-sorrento',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Sorrento',
    circondario: 'Torre Annunziata',
    comune: 'Sorrento',
    provincia: 'NA',
    indirizzo: 'Piazza S. Antonio',
    cap: '80067',
    telefono: '081 8773355 / 65',
    email: 'gdp.sorrento@giustizia.it',
    fax: '081 8071613',
  },
  {
    id: 'gdp-torre-annunziata',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Torre Annunziata',
    circondario: 'Torre Annunziata',
    comune: 'Torre Annunziata',
    provincia: 'NA',
    indirizzo: 'Via Dante, 4',
    cap: '80058',
    telefono: '081 5368221',
    email: 'gdp.torreannunziata@giustizia.it',
    fax: '081 5363887',
  },
  {
    id: 'gdp-torre-del-greco',
    tipo: 'GiudiceDiPace',
    tipoLabel: 'Giudice di Pace',
    denominazione: 'Giudice di Pace di Torre del Greco',
    circondario: 'Torre Annunziata',
    comune: 'Torre del Greco',
    provincia: 'NA',
    indirizzo: 'Via Genova — Parco Cinque, 55',
    cap: '80059',
    telefono: '081 8818017',
    email: 'gdp.torredelgreco@giustizia.it',
    fax: '081 8817984',
  },
];

/**
 * Restituisce l'elenco dei circondari (uffici distrettuali a parte).
 */
export const CIRCONDARI = Array.from(
  new Set(
    RECAPITI_UFFICI
      .map(r => r.circondario)
      .filter((c): c is string => Boolean(c)),
  ),
).sort();
