/**
 * Dislocazione cancellerie e uffici del settore penale del Nuovo Palazzo
 * di Giustizia di Napoli (Tribunale, Corte d'Appello, Tribunale di
 * Sorveglianza, Procura della Repubblica, Procura Generale).
 *
 * Fonte: ricognizione del 03/05/2026 sui siti istituzionali ministeriali.
 * Generato da scripts/genera_uffici_penali.py a partire dal file Excel
 * ubicazione_uffici_penali_nuovo_palazzo_giustizia_napoli.xlsx.
 */

export type EntePenale =
  | 'tribunale'
  | 'corteAppello'
  | 'sorveglianza'
  | 'procura'
  | 'procuraGenerale';

export interface UfficioPenale {
  id: string;
  ente: EntePenale;
  enteLabel: string;
  /** Macro-area funzionale (GIP/GUP, Dibattimento, Riesame, ...) */
  macroArea: string;
  /** Denominazione completa dell'ufficio o della sezione */
  ufficio: string;
  sede: string;
  torre?: string;
  piano?: string;
  stanza?: string;
  ingresso?: string;
  email?: string;
  pec?: string;
  /** Telefono e/o responsabile (campo libero della fonte) */
  telResp?: string;
  /** Note di verifica della fonte (discrasie, dati da confermare) */
  note?: string;
}

export const ENTI_PENALI: { id: EntePenale; label: string; short: string }[] = [
  { id: 'tribunale',       label: 'Tribunale di Napoli',                                          short: 'Tribunale' },
  { id: 'corteAppello',    label: "Corte d'Appello di Napoli",                                  short: "Corte d'Appello" },
  { id: 'sorveglianza',    label: 'Tribunale di Sorveglianza di Napoli',                          short: 'Sorveglianza' },
  { id: 'procura',         label: 'Procura della Repubblica presso il Tribunale di Napoli',       short: 'Procura' },
  { id: 'procuraGenerale', label: "Procura Generale presso la Corte d'Appello di Napoli",       short: 'Procura Generale' },
];

export const UFFICI_PENALI: UfficioPenale[] = [
  {
    id: 'tribunale-front-office-penale',
    ente: 'tribunale' as EntePenale,
    enteLabel: 'Tribunale di Napoli',
    macroArea: 'Front Office Penale',
    ufficio: 'Front Office Penale',
    sede: 'Nuovo Palazzo di Giustizia - Napoli',
    piano: 'Terra',
    ingresso: 'lato Centro Direzionale',
    email: 'frontofficepenale.tribunale.napoli@giustizia.it; frontofficepenalegip.tribunale.napoli@giustizia.it',
    telResp: 'Responsabile: Alessandra Russo',
  },
  {
    id: 'tribunale-coordinamento-settore-gip',
    ente: 'tribunale' as EntePenale,
    enteLabel: 'Tribunale di Napoli',
    macroArea: 'GIP/GUP',
    ufficio: 'Coordinamento settore GIP',
    sede: 'Nuovo Palazzo di Giustizia - Napoli',
    torre: 'Torre B',
    piano: '16',
    email: 'gip.tribunale.napoli@giustizia.it',
    pec: 'gip.tribunale.napoli@giustiziacert.it',
    telResp: 'Responsabile: Nunzia Paudice',
  },
  {
    id: 'tribunale-ruolo-generale-gip',
    ente: 'tribunale' as EntePenale,
    enteLabel: 'Tribunale di Napoli',
    macroArea: 'GIP/GUP',
    ufficio: 'Ruolo Generale GIP',
    sede: 'Nuovo Palazzo di Giustizia - Napoli',
    torre: 'Torre B',
    piano: '15',
    email: 'ruologeneralegip.tribunale.napoli@giustizia.it',
    pec: 'ruologengip.tribunale.napoli@giustiziacert.it',
    telResp: 'Responsabile: Gennaro Simeoli',
  },
  {
    id: 'tribunale-uo-01-02-e-11-gip-gup',
    ente: 'tribunale' as EntePenale,
    enteLabel: 'Tribunale di Napoli',
    macroArea: 'GIP/GUP',
    ufficio: 'UO 01, 02 e 11 GIP/GUP',
    sede: 'Nuovo Palazzo di Giustizia - Napoli',
    torre: 'Torre B',
    piano: '12',
    email: 'primaunitagip.tribunale.napoli@giustizia.it; secondaunitagip.tribunale.napoli@giustizia.it; undicesimaunitagip.tribunale.napoli@giustizia.it',
    telResp: 'Responsabile: Maurizio Fico',
    note: 'Uffici GIP 1-8 e 41-45',
  },
  {
    id: 'tribunale-uo-03-04-e-11-gip-gup',
    ente: 'tribunale' as EntePenale,
    enteLabel: 'Tribunale di Napoli',
    macroArea: 'GIP/GUP',
    ufficio: 'UO 03, 04 e 11 GIP/GUP',
    sede: 'Nuovo Palazzo di Giustizia - Napoli',
    torre: 'Torre B',
    piano: '13',
    email: 'terzaunitagip.tribunale.napoli@giustizia.it; quartaunitagip.tribunale.napoli@giustizia.it; undicesimaunitagip.tribunale.napoli@giustizia.it',
    telResp: 'Responsabile: Olga Molinari',
    note: 'Uffici GIP 9-16 e 41-45',
  },
  {
    id: 'tribunale-uo-05-e-06-gip-gup',
    ente: 'tribunale' as EntePenale,
    enteLabel: 'Tribunale di Napoli',
    macroArea: 'GIP/GUP',
    ufficio: 'UO 05 e 06 GIP/GUP',
    sede: 'Nuovo Palazzo di Giustizia - Napoli',
    torre: 'Torre B',
    piano: '14',
    email: 'quintaunitagip.tribunale.napoli@giustizia.it; sestaunitagip.tribunale.napoli@giustizia.it',
    telResp: 'Responsabile: Natalia Goddi',
    note: 'Uffici GIP 17-24',
  },
  {
    id: 'tribunale-uo-07-08-e-11-gip-gup',
    ente: 'tribunale' as EntePenale,
    enteLabel: 'Tribunale di Napoli',
    macroArea: 'GIP/GUP',
    ufficio: 'UO 07, 08 e 11 GIP/GUP',
    sede: 'Nuovo Palazzo di Giustizia - Napoli',
    torre: 'Torre B',
    piano: '15',
    email: 'settimaunitagip.tribunale.napoli@giustizia.it; ottavaunitagip.tribunale.napoli@giustizia.it; undicesimaunitagip.tribunale.napoli@giustizia.it',
    telResp: 'Responsabile: Anna Daniela Giurato',
    note: 'Uffici GIP 25-32 e 41-45',
  },
  {
    id: 'tribunale-uo-09-e-10-gip-gup',
    ente: 'tribunale' as EntePenale,
    enteLabel: 'Tribunale di Napoli',
    macroArea: 'GIP/GUP',
    ufficio: 'UO 09 e 10 GIP/GUP',
    sede: 'Nuovo Palazzo di Giustizia - Napoli',
    torre: 'Torre B',
    piano: '16',
    email: 'nonaunitagip.tribunale.napoli@giustizia.it; decimaunitagip.tribunale.napoli@giustizia.it; undicesimaunitagip.tribunale.napoli@giustizia.it',
    telResp: 'Responsabile: Daniela Morelli',
    note: 'Uffici GIP 33-41',
  },
  {
    id: 'tribunale-ufficio-liquidazioni-gip',
    ente: 'tribunale' as EntePenale,
    enteLabel: 'Tribunale di Napoli',
    macroArea: 'GIP/GUP',
    ufficio: 'Ufficio Liquidazioni GIP',
    sede: 'Nuovo Palazzo di Giustizia - Napoli',
    torre: 'Torre B',
    piano: '11',
    email: 'istanzewebgip.tribunale.napoli@giustizia.it',
    telResp: 'Responsabile: Gennaro Caputo',
  },
  {
    id: 'tribunale-ufficio-esecuzione-gip',
    ente: 'tribunale' as EntePenale,
    enteLabel: 'Tribunale di Napoli',
    macroArea: 'GIP/GUP',
    ufficio: 'Ufficio Esecuzione GIP',
    sede: 'Nuovo Palazzo di Giustizia - Napoli',
    torre: 'Torre B',
    piano: '12',
    email: 'ufficioesecuzionegip.tribunale.napoli@giustizia.it; ufficioiscrizionegip.tribunale.napoli@giustizia.it',
    pec: 'esecuzionepenale.tribunale.napoli@giustiziacert.it',
    telResp: 'Responsabile: Antonio Maria Di Biasi',
    note: 'Gli indirizzi nel sito presentano spazi interni: qui sono normalizzati',
  },
  {
    id: 'tribunale-registro-generale-dibattimento',
    ente: 'tribunale' as EntePenale,
    enteLabel: 'Tribunale di Napoli',
    macroArea: 'Dibattimento',
    ufficio: 'Registro Generale Dibattimento',
    sede: 'Nuovo Palazzo di Giustizia - Napoli',
    torre: 'Torre B',
    piano: '18',
    email: 'registrodibattimento.tribunale.napoli@giustizia.it',
    pec: 'registrodibattimento.tribunale.napoli@giustiziacert.it',
    telResp: 'Responsabile: Paola Albrizio',
  },
  {
    id: 'tribunale-coordinamento-settore-dibattimento',
    ente: 'tribunale' as EntePenale,
    enteLabel: 'Tribunale di Napoli',
    macroArea: 'Dibattimento',
    ufficio: 'Coordinamento settore Dibattimento',
    sede: 'Nuovo Palazzo di Giustizia - Napoli',
    torre: 'Torre B',
    piano: '22',
    email: 'coordpenale.tribunale.napoli@giustizia.it',
    pec: 'dibattimentopenale.tribunale.napoli@giustiziacert.it',
    telResp: 'Responsabile: Gloria Mantovani',
  },
  {
    id: 'tribunale-sezione-01-e-11-penale',
    ente: 'tribunale' as EntePenale,
    enteLabel: 'Tribunale di Napoli',
    macroArea: 'Dibattimento',
    ufficio: 'Sezione 01 e 11 Penale',
    sede: 'Nuovo Palazzo di Giustizia - Napoli',
    torre: 'Torre B',
    piano: '17',
    email: 'primapenale.tribunale.napoli@giustizia.it; undicesimapenale.tribunale.napoli@giustizia.it',
    pec: 'sez1-11penale.tribunale.napoli@giustiziacert.it',
    telResp: 'Responsabile: Giovanni Bizzarro',
  },
  {
    id: 'tribunale-sezione-misure-di-prevenzione',
    ente: 'tribunale' as EntePenale,
    enteLabel: 'Tribunale di Napoli',
    macroArea: 'Dibattimento',
    ufficio: 'Sezione Misure di Prevenzione',
    sede: 'Nuovo Palazzo di Giustizia - Napoli',
    torre: 'Torre B',
    piano: '23',
    email: 'secondapenale.tribunale.napoli@giustizia.it; misurediprevenzione.tribunale.napoli@giustizia.it',
    pec: 'misurediprevenzione.tribunale.napoli@giustiziacert.it',
    telResp: 'Responsabile: Antonella Caricato',
    note: 'Nel prospetto di dislocazione è indicata come Sezione misure di prevenzione',
  },
  {
    id: 'tribunale-sezione-03-e-05-penale',
    ente: 'tribunale' as EntePenale,
    enteLabel: 'Tribunale di Napoli',
    macroArea: 'Dibattimento',
    ufficio: 'Sezione 03 e 05 Penale',
    sede: 'Nuovo Palazzo di Giustizia - Napoli',
    torre: 'Torre B',
    piano: '20',
    email: 'terzapenale.tribunale.napoli@giustizia.it; quintapenale.tribunale.napoli@giustizia.it',
    pec: 'sez3-5penale.tribunale.napoli@giustiziacert.it',
    telResp: 'Responsabile: Tiziana D\'Amato',
  },
  {
    id: 'tribunale-sezione-04-e-07-penale',
    ente: 'tribunale' as EntePenale,
    enteLabel: 'Tribunale di Napoli',
    macroArea: 'Dibattimento',
    ufficio: 'Sezione 04 e 07 Penale',
    sede: 'Nuovo Palazzo di Giustizia - Napoli',
    torre: 'Torre B',
    piano: '18',
    email: 'quartapenale.tribunale.napoli@giustizia.it; settimapenale.tribunale.napoli@giustizia.it',
    pec: 'sez4-7penale.tribunale.napoli@giustiziacert.it',
    telResp: 'Responsabile: Massimo Senese',
  },
  {
    id: 'tribunale-sezione-06-e-09-penale',
    ente: 'tribunale' as EntePenale,
    enteLabel: 'Tribunale di Napoli',
    macroArea: 'Dibattimento',
    ufficio: 'Sezione 06 e 09 Penale',
    sede: 'Nuovo Palazzo di Giustizia - Napoli',
    torre: 'Torre B',
    piano: '21',
    email: 'sestapenale.tribunale.napoli@giustizia.it; nonapenale.tribunale.napoli@giustizia.it',
    pec: 'sez6-9penale.tribunale.napoli@giustiziacert.it',
    telResp: 'Responsabile: Tiziana D\'Amato',
  },
  {
    id: 'tribunale-ufficio-impugnazioni-dibattimento',
    ente: 'tribunale' as EntePenale,
    enteLabel: 'Tribunale di Napoli',
    macroArea: 'Dibattimento',
    ufficio: 'Ufficio Impugnazioni Dibattimento',
    sede: 'Nuovo Palazzo di Giustizia - Napoli',
    torre: 'Torre B',
    piano: '21',
    email: 'impugnazionidib.tribunale.napoli@giustizia.it',
  },
  {
    id: 'tribunale-ufficio-liquidazioni-dibattimento',
    ente: 'tribunale' as EntePenale,
    enteLabel: 'Tribunale di Napoli',
    macroArea: 'Dibattimento',
    ufficio: 'Ufficio Liquidazioni Dibattimento',
    sede: 'Nuovo Palazzo di Giustizia - Napoli',
    torre: 'Torre B',
    piano: '21',
    telResp: 'Responsabile: Gloria Mantovani',
  },
  {
    id: 'tribunale-ufficio-esecuzione-dibattimento',
    ente: 'tribunale' as EntePenale,
    enteLabel: 'Tribunale di Napoli',
    macroArea: 'Dibattimento',
    ufficio: 'Ufficio Esecuzione Dibattimento',
    sede: 'Nuovo Palazzo di Giustizia - Napoli',
    torre: 'Torre B',
    piano: '17',
    email: 'esecuzionepenale.tribunale.napoli@giustizia.it; iscrizionedibattimento.tribunale.napoli@giustizia.it',
    pec: 'esecuzionepenale.tribunale.napoli@giustiziacert.it',
    telResp: 'Responsabile: Giuseppina De Cicco',
    note: 'Gli indirizzi nel sito presentano spazi interni: qui sono normalizzati',
  },
  {
    id: 'tribunale-corte-di-assise',
    ente: 'tribunale' as EntePenale,
    enteLabel: 'Tribunale di Napoli',
    macroArea: 'Dibattimento',
    ufficio: 'Corte di Assise',
    sede: 'Nuovo Palazzo di Giustizia - Napoli',
    torre: 'Torre B',
    piano: '19',
    email: 'corteassise.tribunale.napoli@giustizia.it',
    pec: 'corteassise.tribunale.napoli@giustiziacert.it',
    telResp: 'Responsabile: Daniela Bellastella',
  },
  {
    id: 'tribunale-sezione-centralizzata-riesame',
    ente: 'tribunale' as EntePenale,
    enteLabel: 'Tribunale di Napoli',
    macroArea: 'Riesame',
    ufficio: 'Sezione Centralizzata Riesame',
    sede: 'Nuovo Palazzo di Giustizia - Napoli',
    torre: 'Torre B',
    piano: '5',
    email: 'riesame.tribunale.napoli@giustizia.it',
    pec: 'riesame.tribunale.napoli@giustiziacert.it',
    telResp: 'Responsabile: Elisabetta Aruta',
  },
  {
    id: 'tribunale-sezione-riesame-08',
    ente: 'tribunale' as EntePenale,
    enteLabel: 'Tribunale di Napoli',
    macroArea: 'Riesame',
    ufficio: 'Sezione Riesame 08',
    sede: 'Nuovo Palazzo di Giustizia - Napoli',
    torre: 'Torre C',
    piano: '5',
    email: 'ottavariesame.tribunale.napoli@giustizia.it',
    pec: 'ottavariesame.tribunale.napoli@giustiziacert.it',
    telResp: 'Responsabile: Raffaela Marino',
  },
  {
    id: 'tribunale-sezione-riesame-10',
    ente: 'tribunale' as EntePenale,
    enteLabel: 'Tribunale di Napoli',
    macroArea: 'Riesame',
    ufficio: 'Sezione Riesame 10',
    sede: 'Nuovo Palazzo di Giustizia - Napoli',
    torre: 'Torre C',
    piano: '5',
    email: 'decimariesame.tribunale.napoli@giustizia.it',
    pec: 'decimariesame.tribunale.napoli@giustiziacert.it',
    telResp: 'Responsabile: Tiziana Ghiggino',
  },
  {
    id: 'tribunale-sezione-riesame-12',
    ente: 'tribunale' as EntePenale,
    enteLabel: 'Tribunale di Napoli',
    macroArea: 'Riesame',
    ufficio: 'Sezione Riesame 12',
    sede: 'Nuovo Palazzo di Giustizia - Napoli',
    torre: 'Torre C',
    piano: '5',
    email: 'dodicesimariesame.tribunale.napoli@giustizia.it',
    pec: 'dodicesimariesame.tribunale.napoli@giustiziacert.it',
    telResp: 'Responsabile: Armando Ruocco',
  },
  {
    id: 'tribunale-sezione-stralcio',
    ente: 'tribunale' as EntePenale,
    enteLabel: 'Tribunale di Napoli',
    macroArea: 'Dibattimento',
    ufficio: 'Sezione Stralcio',
    sede: 'Nuovo Palazzo di Giustizia - Napoli',
    torre: 'Torre B',
    piano: '19',
    email: 'sezionestralciopenale.tribunale.napoli@giustizia.it',
    telResp: 'Responsabile: Luigi Esposito',
  },
  {
    id: 'corteAppello-ufficio-del-coordinatore-settore-penale',
    ente: 'corteAppello' as EntePenale,
    enteLabel: 'Corte d\'Appello di Napoli',
    macroArea: 'Settore Penale',
    ufficio: 'Ufficio del Coordinatore Settore Penale',
    sede: 'Piazza Porzio c/o Nuovo Palazzo di Giustizia',
    torre: 'Torre C',
    piano: '13',
    telResp: 'Responsabile: Lucia Piscitelli; tel. 0812234497',
  },
  {
    id: 'corteAppello-registro-generale-penale',
    ente: 'corteAppello' as EntePenale,
    enteLabel: 'Corte d\'Appello di Napoli',
    macroArea: 'Settore Penale',
    ufficio: 'Registro Generale Penale',
    sede: 'Piazza Porzio c/o Nuovo Palazzo di Giustizia',
    torre: 'Torre C',
    piano: '13',
    email: 'registrogenerale.ca.napoli@giustizia.it',
    pec: 'registrogenerale.penale.ca.napoli@giustiziacert.it',
    telResp: 'Responsabile: Lucia Piscitelli; tel. 0812234497',
  },
  {
    id: 'corteAppello-ufficio-unico-trasmissione-atti-in-cassazione',
    ente: 'corteAppello' as EntePenale,
    enteLabel: 'Corte d\'Appello di Napoli',
    macroArea: 'Cassazione',
    ufficio: 'Ufficio Unico Trasmissione Atti in Cassazione',
    sede: 'Piazza Porzio c/o Nuovo Palazzo di Giustizia',
    torre: 'Torre A',
    piano: '1',
    email: 'ufficiocassazioneinvio.ca.napoli@giustizia.it',
    pec: 'depositoattipenali.ca.napoli@giustiziacert.it',
    telResp: 'Responsabile: Stefania De Falco Giannone',
  },
  {
    id: 'corteAppello-ufficio-unico-trattazione-fascicoli-trasmessi-dalla-cassazione',
    ente: 'corteAppello' as EntePenale,
    enteLabel: 'Corte d\'Appello di Napoli',
    macroArea: 'Cassazione',
    ufficio: 'Ufficio Unico Trattazione Fascicoli Trasmessi dalla Cassazione',
    sede: 'Piazza Porzio c/o Nuovo Palazzo di Giustizia',
    torre: 'Torre A',
    piano: '1',
    email: 'ufficiocassazioneritorno.ca.napoli@giustizia.it',
    pec: 'ritornocassazione.ca.napoli@giustiziacert.it',
    telResp: 'Responsabile: Mario Paesano',
  },
  {
    id: 'corteAppello-ufficio-recupero-crediti-penale',
    ente: 'corteAppello' as EntePenale,
    enteLabel: 'Corte d\'Appello di Napoli',
    macroArea: 'Settore Penale',
    ufficio: 'Ufficio Recupero Crediti Penale',
    sede: 'Piazza Porzio c/o Nuovo Palazzo di Giustizia',
    torre: 'Torre C',
    piano: '2',
    email: 'campione.ca.napoli@giustizia.it',
    pec: 'recuperocrediti.ca.napoli@giustiziacert.it',
  },
  {
    id: 'corteAppello-ufficio-iscrizioni-e-esecuzioni',
    ente: 'corteAppello' as EntePenale,
    enteLabel: 'Corte d\'Appello di Napoli',
    macroArea: 'Esecuzioni',
    ufficio: 'Ufficio Iscrizioni e Esecuzioni',
    sede: 'Piazza Porzio c/o Nuovo Palazzo di Giustizia',
    torre: 'Torre C',
    piano: '13',
    email: 'iscrizione.ca.napoli@giustizia.it',
    pec: 'esecuzionepenale.ca.napoli@giustiziacert.it',
    telResp: 'Responsabile: Rosa Fimiani',
  },
  {
    id: 'corteAppello-ufficio-unico-per-la-trattazione-delle-procedure-incidentali',
    ente: 'corteAppello' as EntePenale,
    enteLabel: 'Corte d\'Appello di Napoli',
    macroArea: 'Esecuzioni',
    ufficio: 'Ufficio Unico per la Trattazione delle Procedure Incidentali',
    sede: 'Piazza Porzio c/o Nuovo Palazzo di Giustizia',
    torre: 'Torre C',
    piano: '13',
    email: 'esec.incesecuzione.ca.napoli@giustizia.it',
    pec: 'incidentiesecuzioni.ca.napoli@giustiziacert.it',
    telResp: 'Responsabile: Maddalena Merito',
  },
  {
    id: 'corteAppello-archivio-generale-penale',
    ente: 'corteAppello' as EntePenale,
    enteLabel: 'Corte d\'Appello di Napoli',
    macroArea: 'Archivio',
    ufficio: 'Archivio Generale Penale',
    sede: 'Piazza Porzio c/o Nuovo Palazzo di Giustizia',
    torre: 'Torre C',
    piano: '13',
    email: 'archiviopenale.ca.napoli@giustizia.it',
    telResp: 'Responsabile: Marcella De Masi; tel. 0812234056',
  },
  {
    id: 'corteAppello-area-prima-e-seconda-sezione-penale',
    ente: 'corteAppello' as EntePenale,
    enteLabel: 'Corte d\'Appello di Napoli',
    macroArea: 'Sezioni Penali',
    ufficio: 'Area Prima e Seconda Sezione Penale',
    sede: 'Piazza Porzio c/o Nuovo Palazzo di Giustizia',
    torre: 'Torre C',
    piano: '14',
    email: 'sez1.penale.ca.napoli@giustizia.it; sez2.penale.ca.napoli@giustizia.it',
    pec: 'sez1.penale.ca.napoli@giustiziacert.it; sez2.penale.ca.napoli@giustiziacert.it; depositoattipenali2.ca.napoli@giustiziacert.it',
    note: 'Orario al pubblico indicato: lun-ven 09:00-12:30',
  },
  {
    id: 'corteAppello-area-terza-e-sesta-sezione-penale',
    ente: 'corteAppello' as EntePenale,
    enteLabel: 'Corte d\'Appello di Napoli',
    macroArea: 'Sezioni Penali',
    ufficio: 'Area Terza e Sesta Sezione Penale',
    sede: 'Piazza Porzio c/o Nuovo Palazzo di Giustizia',
    torre: 'Torre C',
    piano: '15 / 16',
    email: 'sez3.penale.ca.napoli@giustizia.it; sez6.penale.ca.napoli@giustizia.it',
    pec: 'sez3.penale.ca.napoli@giustiziacert.it; sez6.penale.ca.napoli@giustiziacert.it; depositoattipenali3.ca.napoli@giustiziacert.it',
    note: 'Discrasia tra fonti ufficiali: pagina \'Settore Penale\' indica Piano 15; pagina \'Uffici/Cancellerie\' indica Piano 16. Verifica in loco/centralino consigliata.',
  },
  {
    id: 'corteAppello-area-quarta-e-quinta-sezione-penale',
    ente: 'corteAppello' as EntePenale,
    enteLabel: 'Corte d\'Appello di Napoli',
    macroArea: 'Sezioni Penali',
    ufficio: 'Area Quarta e Quinta Sezione Penale',
    sede: 'Piazza Porzio c/o Nuovo Palazzo di Giustizia',
    torre: 'Torre C',
    piano: '15',
    email: 'sez4.penale.ca.napoli@giustizia.it; sez5.penale.ca.napoli@giustizia.it',
    pec: 'sez4.penale.ca.napoli@giustiziacert.it; sez5.penale.ca.napoli@giustiziacert.it; depositoattipenali4.ca.napoli@giustiziacert.it',
  },
  {
    id: 'corteAppello-misure-di-prevenzione-collegio-riparazione-ingiusta-detenzione',
    ente: 'corteAppello' as EntePenale,
    enteLabel: 'Corte d\'Appello di Napoli',
    macroArea: 'Misure di prevenzione',
    ufficio: 'Misure di Prevenzione / Collegio riparazione ingiusta detenzione',
    sede: 'Piazza Porzio c/o Nuovo Palazzo di Giustizia',
    torre: 'Torre C',
    piano: '13',
    email: 'sez8.penale.ca.napoli@giustizia.it',
    pec: 'sez8.penale.ca.napoli@giustiziacert.it; mandatoarrestoeuropeo.ca.napoli@giustiziacert.it; depositoattipenali6.ca.napoli@giustiziacert.it',
    telResp: 'Responsabile: Laura Ferrante; tel. 0812234529',
  },
  {
    id: 'corteAppello-corte-di-assise-di-appello',
    ente: 'corteAppello' as EntePenale,
    enteLabel: 'Corte d\'Appello di Napoli',
    macroArea: 'Corte Assise Appello',
    ufficio: 'Corte di Assise di Appello',
    sede: 'Piazza Porzio c/o Nuovo Palazzo di Giustizia',
    torre: 'Torre C',
    piano: '17',
    email: 'assise.appello.ca.napoli@giustizia.it',
    pec: 'assiseappello.ca.napoli@giustiziacert.it; depositoattipenali5.ca.napoli@giustiziacert.it',
    telResp: 'Responsabile: Marcella De Masi; tel. 0812234617',
    note: 'La pagina settore penale colloca la Corte Assise Appello al Piano 17',
  },
  {
    id: 'sorveglianza-tribunale-e-ufficio-di-sorveglianza-sede',
    ente: 'sorveglianza' as EntePenale,
    enteLabel: 'Tribunale di Sorveglianza di Napoli',
    macroArea: 'Sede',
    ufficio: 'Tribunale e Ufficio di Sorveglianza - sede',
    sede: 'Piazza Porzio / Piazza Falcone e Borsellino c/o Nuovo Palazzo di Giustizia',
    torre: 'Torre C',
    piano: '7 e 8',
    note: 'Sito presso la Corte d\'Appello di Napoli, Torre C, piani 7 e 8',
  },
  {
    id: 'sorveglianza-presidenza',
    ente: 'sorveglianza' as EntePenale,
    enteLabel: 'Tribunale di Sorveglianza di Napoli',
    macroArea: 'Presidenza',
    ufficio: 'Presidenza',
    sede: 'Nuovo Palazzo di Giustizia',
    torre: 'Torre C',
    piano: '8',
    stanza: '3',
    email: 'presidenza.tribsorv.napoli@giustizia.it',
    telResp: 'tel. 0812234279',
  },
  {
    id: 'sorveglianza-ufficio-di-presidenza',
    ente: 'sorveglianza' as EntePenale,
    enteLabel: 'Tribunale di Sorveglianza di Napoli',
    macroArea: 'Presidenza',
    ufficio: 'Ufficio di Presidenza',
    sede: 'Nuovo Palazzo di Giustizia',
    torre: 'Torre C',
    piano: '8',
    stanza: '1',
    email: 'presidenza.tribsorv.napoli@giustizia.it',
    telResp: 'tel. 0812234279 / 0812234275',
  },
  {
    id: 'sorveglianza-cancelleria-centrale-tribunale-e-ufficio-di-sorveglianza',
    ente: 'sorveglianza' as EntePenale,
    enteLabel: 'Tribunale di Sorveglianza di Napoli',
    macroArea: 'Cancelleria centrale',
    ufficio: 'Cancelleria Centrale Tribunale e Ufficio di Sorveglianza',
    sede: 'Nuovo Palazzo di Giustizia',
    torre: 'Torre C',
    piano: '7',
    stanza: '21/22',
    telResp: 'Responsabile: Roberto Corsini; tel. 0812234254',
  },
  {
    id: 'sorveglianza-ruolo-generale',
    ente: 'sorveglianza' as EntePenale,
    enteLabel: 'Tribunale di Sorveglianza di Napoli',
    macroArea: 'Cancelleria centrale',
    ufficio: 'Ruolo Generale',
    sede: 'Nuovo Palazzo di Giustizia',
    torre: 'Torre C',
    piano: '7',
    stanza: '18/19',
    note: 'La pagina rinvia alla sezione modalità di deposito telematico atti',
  },
  {
    id: 'sorveglianza-settore-istruttoria-tribunale-e-ufficio-di-sorveglianza',
    ente: 'sorveglianza' as EntePenale,
    enteLabel: 'Tribunale di Sorveglianza di Napoli',
    macroArea: 'Istruttoria',
    ufficio: 'Settore Istruttoria - Tribunale e Ufficio di Sorveglianza',
    sede: 'Nuovo Palazzo di Giustizia',
    torre: 'Torre C',
    piano: '8',
    stanza: '21/22',
    telResp: 'Responsabile: Elena Geraci; tel. 0812234266',
  },
  {
    id: 'sorveglianza-collegio-1',
    ente: 'sorveglianza' as EntePenale,
    enteLabel: 'Tribunale di Sorveglianza di Napoli',
    macroArea: 'Cancelleria Tribunale di Sorveglianza',
    ufficio: 'Collegio 1',
    sede: 'Nuovo Palazzo di Giustizia',
    torre: 'Torre C',
    piano: '8',
    stanza: '16',
    pec: 'sez1.tribsorv.napoli@giustiziacert.it',
    telResp: 'Referente: Raffaella Porzio; tel. 0812234289',
  },
  {
    id: 'sorveglianza-collegio-2',
    ente: 'sorveglianza' as EntePenale,
    enteLabel: 'Tribunale di Sorveglianza di Napoli',
    macroArea: 'Cancelleria Tribunale di Sorveglianza',
    ufficio: 'Collegio 2',
    sede: 'Nuovo Palazzo di Giustizia',
    torre: 'Torre C',
    piano: '8',
    stanza: '14',
    pec: 'sez2.tribsorv.napoli@giustiziacert.it',
    telResp: 'Referente: Annarita Balzano; tel. 0812234660',
  },
  {
    id: 'sorveglianza-collegio-3',
    ente: 'sorveglianza' as EntePenale,
    enteLabel: 'Tribunale di Sorveglianza di Napoli',
    macroArea: 'Cancelleria Tribunale di Sorveglianza',
    ufficio: 'Collegio 3',
    sede: 'Nuovo Palazzo di Giustizia',
    torre: 'Torre C',
    piano: '7',
    stanza: '12',
    pec: 'sez3.tribsorv.napoli@giustiziacert.it',
    telResp: 'Referente: Arianna Mazzone; tel. 0812234958',
  },
  {
    id: 'sorveglianza-collegio-4',
    ente: 'sorveglianza' as EntePenale,
    enteLabel: 'Tribunale di Sorveglianza di Napoli',
    macroArea: 'Cancelleria Tribunale di Sorveglianza',
    ufficio: 'Collegio 4',
    sede: 'Nuovo Palazzo di Giustizia',
    torre: 'Torre C',
    piano: '7',
    stanza: '14',
    pec: 'sez4.tribsorv.napoli@giustiziacert.it',
    telResp: 'Referente: Marcella Assanti Gironda; tel. 0812234248',
  },
  {
    id: 'sorveglianza-collegio-5',
    ente: 'sorveglianza' as EntePenale,
    enteLabel: 'Tribunale di Sorveglianza di Napoli',
    macroArea: 'Cancelleria Tribunale di Sorveglianza',
    ufficio: 'Collegio 5',
    sede: 'Nuovo Palazzo di Giustizia',
    torre: 'Torre C',
    piano: '8',
    stanza: '15',
    pec: 'sez5.tribsorv.napoli@giustiziacert.it',
    telResp: 'Referente: Federica Ferrara; tel. 0812234288',
  },
  {
    id: 'sorveglianza-cancelleria-ufficio-di-sorveglianza-detenuti',
    ente: 'sorveglianza' as EntePenale,
    enteLabel: 'Tribunale di Sorveglianza di Napoli',
    macroArea: 'Istruttoria',
    ufficio: 'Cancelleria Ufficio di Sorveglianza - Detenuti',
    sede: 'Nuovo Palazzo di Giustizia',
    torre: 'Torre C',
    piano: '8',
    stanza: '18/19',
    pec: 'sez1.tribsorv.napoli@giustiziacert.it',
  },
  {
    id: 'sorveglianza-cancelleria-ufficio-di-sorveglianza-misure-alternative',
    ente: 'sorveglianza' as EntePenale,
    enteLabel: 'Tribunale di Sorveglianza di Napoli',
    macroArea: 'Istruttoria',
    ufficio: 'Cancelleria Ufficio di Sorveglianza - Misure Alternative',
    sede: 'Nuovo Palazzo di Giustizia',
    torre: 'Torre C',
    piano: '8',
    stanza: '23',
    pec: 'sez4.tribsorv.napoli@giustiziacert.it',
  },
  {
    id: 'sorveglianza-cancelleria-ufficio-di-sorveglianza-liberazioni-anticipate',
    ente: 'sorveglianza' as EntePenale,
    enteLabel: 'Tribunale di Sorveglianza di Napoli',
    macroArea: 'Istruttoria',
    ufficio: 'Cancelleria Ufficio di Sorveglianza - Liberazioni Anticipate',
    sede: 'Nuovo Palazzo di Giustizia',
    torre: 'Torre C',
    piano: '8',
    stanza: '24',
    pec: 'sez3.tribsorv.napoli@giustiziacert.it',
  },
  {
    id: 'sorveglianza-cancelleria-ufficio-di-sorveglianza-misure-di-sicurezza',
    ente: 'sorveglianza' as EntePenale,
    enteLabel: 'Tribunale di Sorveglianza di Napoli',
    macroArea: 'Istruttoria',
    ufficio: 'Cancelleria Ufficio di Sorveglianza - Misure di Sicurezza',
    sede: 'Nuovo Palazzo di Giustizia',
    torre: 'Torre C',
    piano: '8',
    stanza: '26',
    pec: 'sez1.tribsorv.napoli@giustiziacert.it',
  },
  {
    id: 'sorveglianza-settore-esecuzione-responsabile',
    ente: 'sorveglianza' as EntePenale,
    enteLabel: 'Tribunale di Sorveglianza di Napoli',
    macroArea: 'Esecuzione',
    ufficio: 'Settore Esecuzione - responsabile',
    sede: 'Nuovo Palazzo di Giustizia',
    torre: 'Torre C',
    piano: '7',
    stanza: '27',
    telResp: 'Referente/Resp.: Stefania Di Cerbo; tel. 0812234257',
  },
  {
    id: 'sorveglianza-settore-esecuzione-detenuti',
    ente: 'sorveglianza' as EntePenale,
    enteLabel: 'Tribunale di Sorveglianza di Napoli',
    macroArea: 'Esecuzione',
    ufficio: 'Settore Esecuzione - Detenuti',
    sede: 'Nuovo Palazzo di Giustizia',
    torre: 'Torre C',
    piano: '7',
    stanza: '27',
    telResp: 'Referente/Resp.: Mariangela Viti; tel. 0812234257',
  },
  {
    id: 'sorveglianza-settore-esecuzione-misure-alternative',
    ente: 'sorveglianza' as EntePenale,
    enteLabel: 'Tribunale di Sorveglianza di Napoli',
    macroArea: 'Esecuzione',
    ufficio: 'Settore Esecuzione - Misure Alternative',
    sede: 'Nuovo Palazzo di Giustizia',
    torre: 'Torre C',
    piano: '7',
    stanza: '1',
    telResp: 'Referente/Resp.: Pasquale Napolitano; tel. 0812234236',
  },
  {
    id: 'sorveglianza-settore-esecuzione-liberazioni-anticipate',
    ente: 'sorveglianza' as EntePenale,
    enteLabel: 'Tribunale di Sorveglianza di Napoli',
    macroArea: 'Esecuzione',
    ufficio: 'Settore Esecuzione - Liberazioni Anticipate',
    sede: 'Nuovo Palazzo di Giustizia',
    torre: 'Torre C',
    piano: '7',
    stanza: '31',
    telResp: 'Referente/Resp.: Maria Antonietta Ainora; tel. 0812234281',
  },
  {
    id: 'sorveglianza-settore-esecuzione-misure-di-sicurezza',
    ente: 'sorveglianza' as EntePenale,
    enteLabel: 'Tribunale di Sorveglianza di Napoli',
    macroArea: 'Esecuzione',
    ufficio: 'Settore Esecuzione - Misure di Sicurezza',
    sede: 'Nuovo Palazzo di Giustizia',
    torre: 'Torre C',
    piano: '7',
    stanza: '2',
    telResp: 'Referente/Resp.: Barbara Vastolo; tel. 0812234249',
  },
  {
    id: 'procura-ufficio-del-funzionario-delegato',
    ente: 'procura' as EntePenale,
    enteLabel: 'Procura della Repubblica presso il Tribunale di Napoli',
    macroArea: 'Uffici penali collegati',
    ufficio: 'Ufficio del Funzionario Delegato',
    sede: 'Nuovo Palazzo di Giustizia',
    torre: 'Torre B',
    piano: '10',
  },
  {
    id: 'procura-ufficio-spese-di-giustizia',
    ente: 'procura' as EntePenale,
    enteLabel: 'Procura della Repubblica presso il Tribunale di Napoli',
    macroArea: 'Uffici penali collegati',
    ufficio: 'Ufficio Spese di Giustizia',
    sede: 'Nuovo Palazzo di Giustizia',
    torre: 'Torre B',
    piano: '9',
  },
  {
    id: 'procura-ufficio-notizie-di-reato-ricezione-atti',
    ente: 'procura' as EntePenale,
    enteLabel: 'Procura della Repubblica presso il Tribunale di Napoli',
    macroArea: 'U.N.R.',
    ufficio: 'Ufficio Notizie di Reato - Ricezione Atti',
    sede: 'Nuovo Palazzo di Giustizia',
    torre: 'Torre B',
    piano: '5',
  },
  {
    id: 'procura-ufficio-notizie-di-reato-pareri-riesami-rogatorie-affari-semplici',
    ente: 'procura' as EntePenale,
    enteLabel: 'Procura della Repubblica presso il Tribunale di Napoli',
    macroArea: 'U.N.R.',
    ufficio: 'Ufficio Notizie di Reato - Pareri, Riesami, Rogatorie, Affari Semplici',
    sede: 'Nuovo Palazzo di Giustizia',
    torre: 'Torre B',
    piano: '5',
  },
  {
    id: 'procura-ufficio-notizie-di-reato-registrazioni-seguiti-ric-gip',
    ente: 'procura' as EntePenale,
    enteLabel: 'Procura della Repubblica presso il Tribunale di Napoli',
    macroArea: 'U.N.R.',
    ufficio: 'Ufficio Notizie di Reato - Registrazioni, Seguiti-Ric. GIP',
    sede: 'Nuovo Palazzo di Giustizia',
    torre: 'Torre B',
    piano: '5',
  },
  {
    id: 'procura-ufficio-notizie-di-reato-sequestri-arresti-decessi',
    ente: 'procura' as EntePenale,
    enteLabel: 'Procura della Repubblica presso il Tribunale di Napoli',
    macroArea: 'U.N.R.',
    ufficio: 'Ufficio Notizie di Reato - Sequestri, Arresti, Decessi',
    sede: 'Nuovo Palazzo di Giustizia',
    torre: 'Torre A',
    piano: '5',
    stanza: 'lamellare',
  },
  {
    id: 'procura-ufficio-notizie-di-reato-smistamento',
    ente: 'procura' as EntePenale,
    enteLabel: 'Procura della Repubblica presso il Tribunale di Napoli',
    macroArea: 'U.N.R.',
    ufficio: 'Ufficio Notizie di Reato - Smistamento',
    sede: 'Nuovo Palazzo di Giustizia',
    torre: 'Torre A',
    piano: '5',
    stanza: 'lamellare',
  },
  {
    id: 'procura-sportelleria-unificata-tiap-art-335-c-p-p',
    ente: 'procura' as EntePenale,
    enteLabel: 'Procura della Repubblica presso il Tribunale di Napoli',
    macroArea: 'TIAP / 335 c.p.p.',
    ufficio: 'Sportelleria Unificata TIAP - art. 335 c.p.p.',
    sede: 'Nuovo Palazzo di Giustizia',
    torre: 'Torre B',
    piano: '5',
    ingresso: 'Ingresso Porzio',
  },
  {
    id: 'procura-ufficio-f-u-g-e-modello-42',
    ente: 'procura' as EntePenale,
    enteLabel: 'Procura della Repubblica presso il Tribunale di Napoli',
    macroArea: 'FUG',
    ufficio: 'Ufficio F.U.G. e modello 42',
    sede: 'Nuovo Palazzo di Giustizia',
    torre: 'Torre B',
    piano: '6',
    stanza: 'lamellare',
  },
  {
    id: 'procura-ufficio-dibattimento',
    ente: 'procura' as EntePenale,
    enteLabel: 'Procura della Repubblica presso il Tribunale di Napoli',
    macroArea: 'Dibattimento',
    ufficio: 'Ufficio Dibattimento',
    sede: 'Nuovo Palazzo di Giustizia',
    piano: 'Quota 11.30',
    ingresso: 'Via Grimaldi',
  },
  {
    id: 'procura-ufficio-archivio',
    ente: 'procura' as EntePenale,
    enteLabel: 'Procura della Repubblica presso il Tribunale di Napoli',
    macroArea: 'Archivio',
    ufficio: 'Ufficio Archivio',
    sede: 'Nuovo Palazzo di Giustizia',
    piano: 'Quota 11.30 / 1° piano Torre B',
    ingresso: 'Via Grimaldi',
    note: 'La pagina \'Trova ufficio\' indica Quota 11.30; la scheda \'Visura e copie fascicoli\' indica 1° piano Torre B',
  },
  {
    id: 'procura-sezione-v-ambiente-edilizia-e-urbanistica',
    ente: 'procura' as EntePenale,
    enteLabel: 'Procura della Repubblica presso il Tribunale di Napoli',
    macroArea: 'Sezioni',
    ufficio: 'Sezione V - Ambiente, Edilizia e Urbanistica',
    sede: 'Nuovo Palazzo di Giustizia',
    torre: 'Torre B',
    piano: '10',
  },
  {
    id: 'procura-ufficio-demolizioni',
    ente: 'procura' as EntePenale,
    enteLabel: 'Procura della Repubblica presso il Tribunale di Napoli',
    macroArea: 'Sezioni',
    ufficio: 'Ufficio Demolizioni',
    sede: 'Nuovo Palazzo di Giustizia',
    torre: 'Torre B',
    piano: '10',
    note: 'La pagina organizzazione amministrativa riporta anche Isola E5/B - 2° e 3° piano: dato da verificare per attività specifica',
  },
  {
    id: 'procura-sezione-vi-lavoro-e-colpe-professionali',
    ente: 'procura' as EntePenale,
    enteLabel: 'Procura della Repubblica presso il Tribunale di Napoli',
    macroArea: 'Sezioni',
    ufficio: 'Sezione VI - Lavoro e colpe professionali',
    sede: 'Nuovo Palazzo di Giustizia',
    torre: 'Torre B',
    piano: '8',
  },
  {
    id: 'procura-sezione-vii-sicurezza-urbana',
    ente: 'procura' as EntePenale,
    enteLabel: 'Procura della Repubblica presso il Tribunale di Napoli',
    macroArea: 'Sezioni',
    ufficio: 'Sezione VII - Sicurezza urbana',
    sede: 'Isola E/5',
    torre: 'Palazzina A',
    piano: '5',
  },
  {
    id: 'procura-sezione-viii-misure-di-prevenzione',
    ente: 'procura' as EntePenale,
    enteLabel: 'Procura della Repubblica presso il Tribunale di Napoli',
    macroArea: 'Sezioni',
    ufficio: 'Sezione VIII - Misure di Prevenzione',
    sede: 'Isola E/5',
    torre: 'Palazzina A',
    piano: '7',
  },
  {
    id: 'procura-sezione-x-esecuzione',
    ente: 'procura' as EntePenale,
    enteLabel: 'Procura della Repubblica presso il Tribunale di Napoli',
    macroArea: 'Sezioni',
    ufficio: 'Sezione X - Esecuzione',
    sede: 'Nuovo Palazzo di Giustizia',
    torre: 'Torre B',
    piano: '7',
    email: 'ufficio.esecuzione.procura.napoli@giustizia.it',
    pec: 'esecuzioni.procura.napoli@giustiziacert.it',
    telResp: 'Centralino 0812236111',
  },
  {
    id: 'procuraGenerale-affari-penali',
    ente: 'procuraGenerale' as EntePenale,
    enteLabel: 'Procura Generale presso la Corte d\'Appello di Napoli',
    macroArea: 'Affari penali',
    ufficio: 'Affari Penali',
    sede: 'Piazza Porzio - Nuovo Palazzo di Giustizia',
    torre: 'Torre C',
    piano: '11',
    stanza: '13',
    email: 'affaripenali.pg.napoli@giustizia.it',
    pec: 'affaripenali.pg.napoli@giustiziacert.it; depositoattipenali3.pg.napoli@giustiziacert.it; mandatoarrestoeuropeo.pg.napoli@giustiziacert.it',
    telResp: 'Tel. 0812234397 / 0812234409 / 0812234403 / 0812234404',
  },
  {
    id: 'procuraGenerale-ufficio-esecuzione-penale',
    ente: 'procuraGenerale' as EntePenale,
    enteLabel: 'Procura Generale presso la Corte d\'Appello di Napoli',
    macroArea: 'Esecuzione penale',
    ufficio: 'Ufficio Esecuzione Penale',
    sede: 'Piazza Porzio - Nuovo Palazzo di Giustizia',
    torre: 'Torre C',
    piano: '10',
    note: 'Risultato ufficiale: personale indicato anche in stanze 18-19; verificare stanza dell\'ufficio al momento dell\'accesso',
  },
];
